### PR TITLE
Joining Lobbies Through URL and as Anonymous Users

### PR DESCRIPTION
**Pull request by Grizzlytron**
I implemented the functionality and routing that players which are anonymous need to enter a username through a AnonymousEnteringLobbyPage. Also redirects back to lobbyoverview if there is no lobby with that lobby code which is entered. Please check if something is missing.

Also bootRun the server on the AnonymousJoining-Grizzly Branch, there it is already solved, that a taken playername can't be chosen again.

### CODE REVIEW

**Comment by na50r** [comment]
Comments
* If you register on two clients. Client A makes the lobby and you use the URL given by Client A on Client B, Client B will be able to join as an Anonymous User. What is this intended? If not, it should be easy to implement a check that confirms if the users is actually Anon or not and then use the correct credentials.
* The bug: 'If game ends and owner goes back to lobby page and starts a new game but player remains at result page' not fixed yet. The owner is able to start a new game while player is still on result page. We could perhaps either force player to come back to the lobby page with owner or if 'start game' is pressed again, result page will automatically navigate to game page yet again.
* It'd be neat if Anon Users had their own profile pictures. Can be implemented in a different branch or a different contributor into this branch.
* Join with URL is relatively unintuitive. Usually I'd expect some kind of popup that tells me which URL I have to copy-paste and sent to my friends. It's not immediately obvious that you use the URL of the lobby page to do this. Reason: Because I already have a popup that tells me to copy the lobby code, so why not allow me to copy the whole URL as well?

**Review by na50r — CHANGES_REQUESTED** [review]
Feedback

- I like the `AnonymousEnteringLobbyPage` but the name is a bit too long, lmao. 
- It's neat that I can now just use the URL to directly join, good work. 

Comments & Changes Requested

- [x]  If you register on two clients. Client A makes the lobby and you use the URL given by Client A on Client B, Client B will be able to join as an Anonymous User. What is this intended? If not, it should be easy to implement a check that confirms if the users is actually Anon or not and then use the correct credentials.

- [ ] The bug: 'If game ends and owner goes back to lobby page and starts a new game but player remains at result page' not fixed yet. The owner is able to start a new game while player is still on result page. We could perhaps either force player to come back to the lobby page with owner or if 'start game' is pressed again, result page will automatically navigate to game page yet again.
- [ ]  It'd be neat if Anon Users had their own profile pictures. Can be implemented in a different branch or a different contributor into this branch.
- [ ] Join with URL is relatively unintuitive. Usually I'd expect some kind of popup that tells me which URL I have to copy-paste and sent to my friends. It's not immediately obvious that you use the URL of the lobby page to do this. Reason: Because I already have a popup that tells me to copy the lobby code, so why not allow me to copy the whole URL as well?

**Comment by Grizzlytron** [comment]
Thanks for the feedback.
I implemented it now that registered users can also join through URLs (is a bit ugly but it works).
Also added a penguin picture for anonymous users, not sure whether you wanted random pictures like of different animals for different users or whether you just wanted a single one for all anonymous users. We can still change that easily later.
Concerning the explaining of how to join via URL, i think it makes most sense to keep it as is and add your typewriter to add a hint about how you could join via URL if wanted. Am not sure whether this would be the main way of joining or if just the lobbycode gets exchanged which allow people to join in through the lobbyoverview page.

**Comment by Grizzlytron** [comment]
And about the bug that the game ends: I would change that in another branch, it's not related to what i tried to implement.

**Review by na50r — APPROVED** [review]
Eslint complained on my side, so I fixed up the indendations myself and committed it. On the Server side, I set 'BlueFrog' as the standard profile picture but when a user is created, the profile picture field is left empty and the Client uses the Frog. But with your implementation, if you create a lobby without updating the profile once, the logged in user will be a Penguin.

As for how to setup profile pictures for anonymous players, I might come up with a fix and play with it and add it also as a commit and then you can decide if you want to use it or not. Otherwise, all good.

**Pull request merged**
