### PR TITLE
Profile page na50r

### PR DESCRIPTION
**Pull request by na50r**
I implemented the profile page. I mainly used the mockups as a reference. There were some parts I wasn't too hapy with but for the most part, I think we can actually already use this for M3. 
If you find anything faulty with the code or the overall design, let me know.

https://github.com/sopra-fs24-group-41/sopra-fs24-group-41-client/assets/145561869/148123e7-11a6-47fd-828b-a562fb1da598

### CODE REVIEW

**Review by Tmmn — APPROVED** [review]
works on my device, can't see anything wrong or anything I would change

**Comment by na50r** [comment]
> works on my device, can't see anything wrong or anything I would change

I'm still not quite satisfied yet. I managed to get it working with input="date" (HTML) instead of React datepicker but I'd like to separate the IconImage dropdown menu from the `ProfileIcon.tsx` and thus make it it's own component. Additionally, I still need to configure some stuff for mobile but I should be able to get it done tomorrow and then just work on the `create lobby` screen.

**Comment by na50r** [comment]
Here a demo of current modified version. 

https://github.com/sopra-fs24-group-41/sopra-fs24-group-41-client/assets/145561869/7fbc0792-6481-4978-ad7f-b94dabbaa296

Now I feel more satisfied with merging it. Pls have a look, test it on your machine and if there are no bugs, then we may merge it.

**Review by Tmmn — CHANGES_REQUESTED** [review]
Everything works, except for changing the birth date. It does not get filled in automatically when you start editing the profile for the first time. The value has the wrong format: Sun Apr 01 2001 02:00:00 GMT+0200 (Mitteleuropäische Sommerzeit). The picker only displays values that look like 2001-04-01. And when you empty the field completely with the provided button in the picker, the whole site crashes.

**Comment by Tmmn** [comment]
and did you remove the outline from the lobby selection? Now it is only slighty brighter than the other buttons when you select it, which makes it very hard to distinguish for people with imperfect eyesight

**Pull request merged**
